name: tumitas
description: This application converts tasks into blocks, allowing you to accumulate and visualize your progress. Users can review completed tasks and look back at past accomplishments at a glance.
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: '>=3.1.5 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    intl: ^0.18.1
    uuid: ^4.2.1
    font_awesome_flutter: ^10.6.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    shared_preferences: ^2.2.2
    sqflite: ^2.3.0

    flutter_launcher_icons:

flutter_icons:
    android: true
    ios: true
    image_path: 'assets/images/tumitas_icon.png'
    adaptive_icon_background: '#ffffff'

flutter:
    uses-material-design: true

    assets:
        - assets/images/title_logo.png
        - assets/images/cloud1.png
        - assets/images/cloud2.png
        - assets/images/cloud3.png
        - assets/images/cloud4.png
